install:
	./gradlew install

clean:
	./gradlew clean

compTest:
	./gradlew compileTestJava


test:
	./gradlew test

run-dist:
	./build/install/app/bin/app

lint:
	./gradlew checkstyleMain

update-deps:
	./gradlew useLatestVersions

